### ISSUE TITLE
Object 'school.name' not found

### ISSUE THREAD

**Issue by chapmjs** [nvs-group/epic#12]
I ran the current code from Github on my local machine and found this error:

Listening on http://127.0.0.1:4056
Warning: Error in %in%: object 'school.name' not found
  69: filter_impl
  68: filter.tbl_df
  65: filter.data.frame
  63: <reactive:table_var> [/Users/chapmjs/Dropbox/R-Studio/epic/app.R#389]
  47: table_var
  44: <observer> [/Users/chapmjs/Dropbox/R-Studio/epic/app.R#404]
   1: runApp
Warning: Error in %in%: object 'school.name' not found
  65: <Anonymous>

**Comment by lcchapman** [comment]
The Access database does not allow for "." in the field names. However most of the EPIC files have a "." in their name, including "school.name". Access uses a "-" instead. So the dashes need to be replaced with period before the Master1 file can be compile.
