### ISSUE TITLE
Fix Master1 table

### ISSUE THREAD

**Issue by lcchapman** [nvs-group/epic#14]
Master1 table has type errors and data errors that need to be corrected so that the table can be easily updated and reloaded into the system.

**Comment by chapmjs** [comment]
I unzipped the Master1.zip file and uploaded the master1.txt file to Dropbox.  
I also changed the app.R file to pull the master1.txt from the Dropbox file.
Still get the same error messages when I run the app.

**Comment by lcchapman** [comment]
I finally got it working on my machine, but took some tweaks. How hard it
is to teach me how to load it up on the server where I can try out some
different things. I think you are running into the same problems I ran
into.

**Comment by lcchapman** [comment]
The format of the master1 table is very important. The table must be in "dataframe" format in order to run properly. This format is not "cvs". Rather it is derived from the "csv" file. All of the fields up to and including "cip.cat" must be "character fields". All other fields must be numeric fields. Failure to set these formats will result in fatal errors. Once the "csv" file is created, the following command must be run to create the master1 dataframe: "master1 <- read.csv("Master1.csv")"
