### ISSUE TITLE
ON the web links under the "Tools" tab, open a new window when the link is clicked. 

### ISSUE THREAD

**Issue by lcchapman** [nvs-group/epic#21]
When I click on a link right now, it overwrites the App window and logs me out of the running App. It should open the link in a new window so it doesn't close the App.

**Comment by stevenromriell** [comment]
Ok. Will look into this

**Comment by stevenromriell** [comment]
This statement is an example of an html link:
 h4("Explore career occupations:", a("https://www.onetonline.org/", href = "https://www.onetonline.org/", target = "_blank"))
The 'target = "_blank"' part opens the link in a new window
